const busstations= [
    "Majestic Bus Station, Bangalore",
    "Kempegowda Bus Station, Bangalore",
    "Chennai Mofussil Bus Terminus (CMBT), Chennai",
    "Koyambedu Moffusil Bus Terminus, Chennai",
    "Delhi Integrated Multi-Modal Transit System (DIMTS) Bus Terminals, Delhi",
    "ISBT Kashmiri Gate, Delhi",
    "ISBT Anand Vihar, Delhi",
    "Egmore Bus Stand, Chennai",
    "Chengalpattu Bus Stand, Chennai",
    "Kolkata Esplanade Bus Terminus, Kolkata",
    "Salt Lake Sector V Bus Terminus, Kolkata",
    "Dadar Bus Station, Mumbai",
    "Pune Station Bus Stand, Pune",
    "Swargate Bus Stand, Pune",
    "Thane Railway Station Bus Stand, Mumbai",
    "Hyderabad Mahatma Gandhi Bus Station (MGBS), Hyderabad",
    "Jubilee Bus Station, Hyderabad",
    "Ahmedabad Central Bus Station, Ahmedabad",
    "Surat Central Bus Station, Surat",
    "Gandhinagar Bus Station, Ahmedabad",
    "Jaipur Sindhi Camp Bus Stand, Jaipur",
    "Jaipur Narayan Singh Circle Bus Stand, Jaipur",
    "Lucknow Alambagh Bus Stand, Lucknow",
    "Lucknow Charbagh Bus Stand, Lucknow",
    "Nagpur Ganeshpeth Bus Stand, Nagpur",
    "Nagpur Sitabuldi Bus Stand, Nagpur",
    "Indore Sarwate Bus Stand, Indore",
    "Indore Gangwal Bus Stand, Indore",
    "Kanpur Central Bus Stand, Kanpur",
    "Varanasi Cantt Bus Stand, Varanasi",
    "Ghaziabad New Bus Stand, Ghaziabad",
    "Ghaziabad Old Bus Stand, Ghaziabad",
    "Agra Idgah Bus Stand, Agra",
    "Dehradun ISBT, Dehradun",
    "Rajkot Central Bus Station, Rajkot",
    "Vadodara Central Bus Station, Vadodara",
    "Chandigarh Sector 17 Bus Stand, Chandigarh",
    "Amritsar Bus Stand, Amritsar",
    "Jalandhar Bus Stand, Jalandhar",
    "Ludhiana Bus Stand, Ludhiana",
    "Gurgaon Bus Stand, Gurgaon",
    "Noida Bus Stand, Noida",
    "Faridabad Bus Stand, Faridabad",
    "Gurugram Bus Stand, Gurugram",
    "Patna Gandhi Maidan Bus Stand, Patna",
    "Patna Mithapur Bus Stand, Patna",
    "Ranchi Bus Stand, Ranchi",
    "Bhopal Nadra Bus Stand, Bhopal",
    "Bhopal ISBT, Bhopal",
    "Aurangabad Central Bus Stand, Aurangabad",
    "Nashik Central Bus Stand, Nashik",
    "Navi Mumbai CBD Belapur Bus Station, Navi Mumbai",
    "Navi Mumbai Vashi Bus Station, Navi Mumbai",
    "Thiruvananthapuram Central Bus Station, Thiruvananthapuram",
    "Kochi Vyttila Mobility Hub, Kochi",
    "Kozhikode Mofussil Bus Stand, Kozhikode",
    "Thiruvalla Central Bus Station, Thiruvalla",
    "Thrissur Round Bus Stand, Thrissur",
    "Kollam Bus Stand, Kollam",
    "Kottayam Bus Stand, Kottayam",
    "Kannur Central Bus Station, Kannur",
    "Kasaragod Bus Stand, Kasaragod",
    "Palakkad Central Bus Station, Palakkad",
    "Kollam KSRTC Bus Stand, Kollam",
    "Kozhikode KSRTC Bus Stand, Kozhikode",
    "Kochi KSRTC Bus Stand, Kochi",
    "Thiruvananthapuram KSRTC Bus Stand, Thiruvananthapuram",
    "Bengaluru Kempegowda Bus Station, Bengaluru",
    "Mysuru Central Bus Station, Mysuru",
    "Mangaluru Central Bus Station, Mangaluru",
    "Hubballi Central Bus Station, Hubballi",
    "Belagavi Central Bus Station, Belagavi",
    "Dharwad Central Bus Station, Dharwad",
    "Kalaburagi Central Bus Station, Kalaburagi",
    "Davanagere Central Bus Station, Davanagere",
    "Shivamogga Central Bus Station, Shivamogga",
    "Udupi Central Bus Station, Udupi",
    "Bhadravathi Central Bus Station, Bhadravathi",
    "Hassan Central Bus Station, Hassan",
    "Bagalkot Central Bus Station, Bagalkot",
    "Bijapur Central Bus Station, Bijapur",
    "Bidar Central Bus Station, Bidar",
    "Raichur Central Bus Station, Raichur",
    "Bellary Central Bus Station, Bellary",
    "Gulbarga Central Bus Station, Gulbarga",
    "Karwar Central Bus Station, Karwar",
    "Sirsi Central Bus Station, Sirsi",
    "Tumakuru Central Bus Station, Tumakuru",
    "Hosapete Central Bus Station, Hosapete",
    "Chitradurga Central Bus Station, Chitradurga",
    "Chikkamagaluru Central Bus Station, Chikkamagaluru",
    "Ranebennur Central Bus Station, Ranebennur",
    "Shivamogga KSRTC Bus Stand, Shivamogga",
    "Koppal Central Bus Station, Koppal",
    "Vijayapura Central Bus Station, Vijayapura",
    "Kolar Central Bus Station, Kolar",
    "Mandya Central Bus Station, Mandya",
    "Madikeri Central Bus Station, Madikeri",
    "Chikkaballapur Central Bus Station, Chikkaballapur",
    "Chikkamagaluru Central Bus Station, Chikkamagaluru",
    "Hassan KSRTC Bus Stand, Hassan",
    "Dharwad KSRTC Bus Stand, Dharwad",
    "Belagavi KSRTC Bus Stand, Belagavi",
    "Vijayapura KSRTC Bus Stand, Vijayapura",
    "Davanagere KSRTC Bus Stand, Davanagere",
    "Kalaburagi KSRTC Bus Stand, Kalaburagi",
    "Tumakuru KSRTC Bus Stand, Tumakuru"]
module.exports=busstations