const hotellocations = [
    {"name": "Taj Mahal Palace", "location": "Mumbai"},
    {"name": "The Oberoi", "location": "Mumbai"},
    {"name": "ITC Grand Chola", "location": "Chennai"},
    {"name": "Taj Falaknuma Palace", "location": "Hyderabad"},
    {"name": "The Leela Palace", "location": "New Delhi"},
    {"name": "The Oberoi Udaivilas", "location": "Udaipur"},
    {"name": "The Leela Palace", "location": "Bengaluru"},
    {"name": "Taj Lake Palace", "location": "Udaipur"},
    {"name": "JW Marriott", "location": "Mumbai"},
    {"name": "The Oberoi Rajvilas", "location": "Jaipur"},
    {"name": "Taj Exotica", "location": "Goa"},
    {"name": "The Leela Kovalam", "location": "Kerala"},
    {"name": "Rambagh Palace", "location": "Jaipur"},
    {"name": "Taj West End", "location": "Bengaluru"},
    {"name": "Vivanta by Taj", "location": "Goa"},
    {"name": "Hyatt Regency", "location": "Mumbai"},
    {"name": "Le Meridien", "location": "New Delhi"},
    {"name": "The Imperial", "location": "New Delhi"},
    {"name": "ITC Maurya", "location": "New Delhi"},
    {"name": "Trident", "location": "Mumbai"},
    {"name": "Four Seasons", "location": "Mumbai"},
    {"name": "Radisson Blu", "location": "Jaipur"},
    {"name": "The Lalit", "location": "Mumbai"},
    {"name": "Park Hyatt", "location": "Chennai"},
    {"name": "Sheraton Grand", "location": "Bengaluru"},
    {"name": "Novotel", "location": "Hyderabad"},
    {"name": "Marriott", "location": "Jaipur"},
    {"name": "The Park", "location": "Kolkata"},
    {"name": "ITC Gardenia", "location": "Bengaluru"},
    {"name": "The Gateway", "location": "Varanasi"},
    {"name": "Taj Lands End", "location": "Mumbai"},
    {"name": "Grand Hyatt", "location": "Mumbai"},
    {"name": "The St. Regis", "location": "Mumbai"},
    {"name": "Taj Diplomatic Enclave", "location": "New Delhi"},
    {"name": "Hyatt Regency", "location": "Kolkata"},
    {"name": "The Westin", "location": "Gurgaon"},
    {"name": "The Oberoi Grand", "location": "Kolkata"},
    {"name": "The Lodhi", "location": "New Delhi"},
    {"name": "Vivanta by Taj", "location": "Bengaluru"},
    {"name": "ITC Maratha", "location": "Mumbai"},
    {"name": "Alila Diwa", "location": "Goa"},
    {"name": "The Oberoi Cecil", "location": "Shimla"},
    {"name": "Wildflower Hall", "location": "Shimla"},
    {"name": "The Ritz-Carlton", "location": "Bengaluru"},
    {"name": "Trident", "location": "Udaipur"},
    {"name": "The Claridges", "location": "New Delhi"},
    {"name": "The Suryaa", "location": "New Delhi"},
    {"name": "Leela Ambience", "location": "Gurgaon"},
    {"name": "Vivanta by Taj", "location": "Chennai"},
    {"name": "Eros Hotel", "location": "New Delhi"},
    {"name": "Crowne Plaza", "location": "Jaipur"},
    {"name": "Holiday Inn", "location": "Mumbai"},
    {"name": "Sofitel", "location": "Mumbai"},
    {"name": "The Zuri Whitefield", "location": "Bengaluru"},
    {"name": "Hyatt Place", "location": "Goa"},
    {"name": "Grand Mercure", "location": "Bengaluru"},
    {"name": "Novotel", "location": "Goa"},
    {"name": "The Tamara", "location": "Coorg"},
    {"name": "Radisson Blu", "location": "Mumbai"},
    {"name": "The Gateway", "location": "Chikmagalur"},
    {"name": "The Raintree", "location": "Chennai"},
    {"name": "Ramada", "location": "Jaipur"},
    {"name": "Lemon Tree Premier", "location": "Delhi"},
    {"name": "The Park", "location": "Chennai"},
    {"name": "The Windflower Resort", "location": "Mysuru"},
    {"name": "Gokulam Grand", "location": "Bengaluru"},
    {"name": "DoubleTree by Hilton", "location": "Goa"},
    {"name": "Courtyard by Marriott", "location": "Chennai"},
    {"name": "Radisson Blu", "location": "Chennai"},
    {"name": "The Park", "location": "Hyderabad"},
    {"name": "Ramada", "location": "Kochi"},
    {"name": "Fortune Select Grand", "location": "Chennai"},
    {"name": "Holiday Inn", "location": "Chennai"},
    {"name": "The Bheemli Resort", "location": "Visakhapatnam"},
    {"name": "Trident", "location": "Chennai"},
    {"name": "ibis", "location": "Mumbai"},
    {"name": "The Park", "location": "Bengaluru"},
    {"name": "Le Meridien", "location": "Kochi"},
    {"name": "Crowne Plaza", "location": "Chennai"},
    {"name": "Novotel", "location": "Chennai"},
    {"name": "Holiday Inn", "location": "Kochi"},
    {"name": "Novotel", "location": "Hyderabad"},
    {"name": "Fairfield by Marriott", "location": "Bengaluru"},
    {"name": "Hyatt", "location": "Ahmedabad"},
    {"name": "Radisson Blu", "location": "Pune"},
    {"name": "The Park", "location": "New Delhi"},
    {"name": "JW Marriott", "location": "Pune"},
    {"name": "The Gateway", "location": "Mangalore"},
    {"name": "Fairmont", "location": "Jaipur"},
    {"name": "Vivanta by Taj", "location": "Pune"},
    {"name": "The Lalit", "location": "Jaipur"},
    {"name": "Holiday Inn", "location": "Pune"},
    {"name": "Hyatt Regency", "location": "Pune"},
    {"name": "Courtyard by Marriott", "location": "Pune"},
    {"name": "The Westin", "location": "Pune"},
    {"name": "Sheraton Grand", "location": "Pune"},
    {"name": "Le Meridien", "location": "Pune"}
]
module.exports=hotellocations;