stations = [
    {"code": "NDLS", "name": "New Delhi"},
    {"code": "BCT", "name": "Mumbai Central"},
    {"code": "MAS", "name": "Chennai Central"},
    {"code": "HWH", "name": "Howrah Junction"},
    {"code": "SBC", "name": "Bangalore City"},
    {"code": "PUNE", "name": "Pune Junction"},
    {"code": "ADI", "name": "Ahmedabad Junction"},
    {"code": "SC", "name": "Secunderabad Junction"},
    {"code": "HYB", "name": "Hyderabad Deccan"},
    {"code": "JP", "name": "Jaipur Junction"},
    {"code": "BPL", "name": "Bhopal Junction"},
    {"code": "SDAH", "name": "Kolkata Sealdah"},
    {"code": "LKO", "name": "Lucknow Charbagh"},
    {"code": "PNBE", "name": "Patna Junction"},
    {"code": "CDG", "name": "Chandigarh Junction"},
    {"code": "GHY", "name": "Guwahati"},
    {"code": "TVC", "name": "Trivandrum Central"},
    {"code": "ERS", "name": "Kochi"},
    {"code": "INDB", "name": "Indore Junction"},
    {"code": "ST", "name": "Surat"},
    {"code": "NGP", "name": "Nagpur Junction"},
    {"code": "BRC", "name": "Vadodara Junction"},
    {"code": "BSB", "name": "Varanasi Junction"},
    {"code": "CNB", "name": "Kanpur Central"},
    {"code": "ASR", "name": "Amritsar Junction"},
    {"code": "BBS", "name": "Bhubaneswar"},
    {"code": "AGC", "name": "Agra Cantt"},
    {"code": "JU", "name": "Jodhpur Junction"},
    {"code": "GKP", "name": "Gorakhpur Junction"},
    {"code": "ALD", "name": "Allahabad Junction"},
    {"code": "CBE", "name": "Coimbatore Junction"},
    {"code": "BZA", "name": "Vijayawada Junction"},
    {"code": "TPJ", "name": "Tiruchirapalli Junction"},
    {"code": "R", "name": "Raipur Junction"},
    {"code": "RJT", "name": "Rajkot Junction"},
    {"code": "DHN", "name": "Dhanbad Junction"},
    {"code": "MDU", "name": "Madurai Junction"},
    {"code": "DDN", "name": "Dehradun"},
    {"code": "SINA", "name": "Srinagar"},
    {"code": "TATA", "name": "Jamshedpur"},
    {"code": "MAQ", "name": "Mangalore"},
    {"code": "BE", "name": "Bareilly"},
    {"code": "UDZ", "name": "Udaipur City"},
    {"code": "RNC", "name": "Ranchi"},
    {"code": "GWL", "name": "Gwalior Junction"},
    {"code": "BKN", "name": "Bikaner Junction"},
    {"code": "UMB", "name": "Ambala Cantt"},
    {"code": "BGP", "name": "Bhagalpur"},
    {"code": "SML", "name": "Shimla"},
    {"code": "ALJN", "name": "Aligarh Junction"},
    {"code": "SGUJ", "name": "Siliguri Junction"},
    {"code": "JUC", "name": "Jalandhar City"},
    {"code": "MB", "name": "Moradabad Junction"},
    {"code": "JAT", "name": "Jammu Tawi"},
    {"code": "HSR", "name": "Hisar"},
    {"code": "GAYA", "name": "Gaya Junction"},
    {"code": "DBG", "name": "Darbhanga Junction"},
    {"code": "SA", "name": "Salem Junction"},
    {"code": "JHS", "name": "Jhansi Junction"},
    {"code": "JBP", "name": "Jabalpur Junction"},
    {"code": "QLN", "name": "Kollam Junction"},
    {"code": "ASN", "name": "Asansol Junction"},
    {"code": "DGR", "name": "Durgapur"},
    {"code": "ALLP", "name": "Alappuzha"},
    {"code": "TCR", "name": "Thrissur"},
    {"code": "GNT", "name": "Guntur Junction"},
    {"code": "GTL", "name": "Guntakal Junction"},
    {"code": "BSP", "name": "Bilaspur Junction"},
    {"code": "KGP", "name": "Kharagpur Junction"},
    {"code": "MTJ", "name": "Mathura Junction"},
    {"code": "DBRG", "name": "Dibrugarh Town"},
    {"code": "BHUJ", "name": "Bhuj"},
    {"code": "MFP", "name": "Muzaffarpur Junction"},
    {"code": "DWR", "name": "Dharwad"},
    {"code": "HDW", "name": "Haldwani"},
    {"code": "CCT", "name": "Kakinada Town"},
    {"code": "EE", "name": "Eluru"},
    {"code": "NZB", "name": "Nizamabad"},
    {"code": "KRNT", "name": "Kurnool City"},
    {"code": "TPTY", "name": "Tirupati"},
    {"code": "RTM", "name": "Ratlam Junction"},
    {"code": "AII", "name": "Ajmer Junction"},
    {"code": "PNP", "name": "Panipat Junction"},
    {"code": "BJU", "name": "Barauni Junction"},
    {"code": "KOTA", "name": "Kota Junction"},
    {"code": "PGT", "name": "Palakkad Junction"},
    {"code": "ANVT", "name": "Anand Vihar Terminal"},
    {"code": "BVC", "name": "Bhavnagar Terminus"},
    {"code": "PDY", "name": "Puducherry"},
    {"code": "KTYM", "name": "Kottayam"},
    {"code": "NLR", "name": "Nellore"},
    {"code": "JSG", "name": "Jharsuguda Junction"},
    {"code": "ATP", "name": "Anantapur"},
    {"code": "CHE", "name": "Srikakulam Road"},
    {"code": "VZM", "name": "Vizianagaram Junction"},
    {"code": "ROU", "name": "Rourkela"},
    {"code": "DURG", "name": "Durg Junction"},
    {"code": "BHC", "name": "Bhadrak"},
    {"code": "KIR", "name": "Katihar Junction"},
    {"code": "ROK", "name": "Rohtak Junction"},
    {"code": "BL", "name": "Valsad"},
    {"code": "PNU", "name": "Palanpur Junction"},
    {"code": "BTI", "name": "Bhatinda Junction"},
    {"code": "JL", "name": "Jalgaon Junction"},
    {"code": "CTO", "name": "Chittoor"},
    {"code": "KUR", "name": "Khurda Road Junction"},
    {"code": "SUNR", "name": "Surendranagar Junction"},
    {"code": "TJ", "name": "Thanjavur Junction"},
    {"code": "HSRA", "name": "Hosur"},
    {"code": "RJY", "name": "Rajahmundry"},
    {"code": "PTK", "name": "Pathankot Junction"},
    {"code": "UD", "name": "Udupi"},
    {"code": "CPR", "name": "Chapra"},
    {"code": "PRNA", "name": "Purnia Junction"},
    {"code": "KRMR", "name": "Karimnagar"},
    {"code": "AWB", "name": "Aurangabad"},
    {"code": "GIMB", "name": "Gandhidham Junction"},
    {"code": "RPJ", "name": "Rajpura Junction"},
    {"code": "HJP", "name": "Hajipur Junction"},
    {"code": "TEN", "name": "Tirunelveli Junction"},
    {"code": "SRR", "name": "Shoranur Junction"},
    {"code": "BSL", "name": "Bhusaval Junction"},
    {"code": "NED", "name": "Nanded"},
    {"code": "AD", "name": "Adoni"},
    {"code": "MTM", "name": "Machilipatnam"},
    {"code": "HPT", "name": "Hospet Junction"},
    {"code": "CWA", "name": "Chhindwara Junction"},
    {"code": "AKV", "name": "Ankleshwar Junction"},
    {"code": "KSN", "name": "Krishna"},
    {"code": "DGR", "name": "Durgapur"},
    {"code": "BAY", "name": "Bellary Junction"},
    {"code": "SIKR", "name": "Sikar Junction"},
    {"code": "MDS", "name": "Mandsaur"},
    {"code": "BWS", "name": "Banswara"},
    {"code": "FZR", "name": "Firozpur Cantt"},
    {"code": "YJUD", "name": "Yamunanagar Jagadhri"},
    {"code": "KOP", "name": "Kolhapur"},
    {"code": "KTYM", "name": "Kottayam"},
    {"code": "BKSC", "name": "Bokaro Steel City"},
    {"code": "MOZ", "name": "Muzaffarnagar"},
    {"code": "KTE", "name": "Katni Junction"},
    {"code": "GGC", "name": "Gangapur City"},
    {"code": "BME", "name": "Barmer"},
    {"code": "BSP", "name": "Bilaspur Road"},
    {"code": "OGL", "name": "Ongole"},
    {"code": "BPO", "name": "Baripada"},
    {"code": "VDG", "name": "Virudhunagar Junction"},
    {"code": "NK", "name": "Nashik Road"},
    {"code": "GDA", "name": "Godhra Junction"},
    {"code": "RE", "name": "Rewari"},
    {"code": "BGP", "name": "Bhagalpur"},
    {"code": "PBE", "name": "Pilibhit Junction"},
    {"code": "RBL", "name": "Rae Bareli Junction"},
    {"code": "BSR", "name": "Vasai Road"},
    {"code": "RKSH", "name": "Rishikesh"},
    {"code": "BJP", "name": "Vijayapura"},
    {"code": "AMI", "name": "Amravati"},
    {"code": "NLDA", "name": "Nalgonda"},
    {"code": "TUP", "name": "Tiruppur"},
    {"code": "MMR", "name": "Manmad Junction"},
    {"code": "BZU", "name": "Betul"},
    {"code": "MZP", "name": "Mirzapur"},
    {"code": "HAS", "name": "Hassan"},
    {"code": "RXL", "name": "Raxaul Junction"},
    {"code": "TEL", "name": "Tenali Junction"},
    {"code": "ARJ", "name": "Auraiya"},
    {"code": "BBK", "name": "Barabanki Junction"},
    {"code": "BHUJ", "name": "Bhuj"},
    {"code": "DWK", "name": "Dwarka"},
]

module.exports=stations